### ISSUE TITLE
Toggle automatic clipping button freezes occasionally in Blender 3.3.1

### ISSUE THREAD

**Issue by Intuos5** [kromar/blender_clipping_assistant#9]
The toggle automatic clipping button occasionally freezes in Blender 3.1.1 on Windows 10. To circumvent this, I have to deselect the object and reselect it before I can use the button again.

**Comment by kromar** [comment]
Thanks for reporting this issue, i noticed that this also happens sometimes when i load a new file but your additional information should help to find a solution for this issue.

**Comment by kromar** [comment]
I fixed a issue with the button indicating the wrong status, would be great if you could try this and see if this also fixes your issue. If not i will need some more details how this can be reproduced as i never had the issue you describe happening to me.
https://github.com/kromar/blender_clipping_assistant/releases/tag/v2_0_6

**Comment by Intuos5** [comment]
Thanks for the help, I think I may have discovered the reason for the button freezing. 

I see the reason for the clipping button freezing, it happens when the object or collection that the object resides in is set to be unselectable in the outliner. 

https://user-images.githubusercontent.com/63149655/232331845-9ead9b1d-32d8-4f41-9d78-d6f3f181d538.mp4

**Comment by kromar** [comment]
Thanks for sharing this, i am able to reproduce the issue with this and should be able to find a fix for it.

**Comment by kromar** [comment]
After more testing there is something strange happening from blenders side which does not let me fix this in a satisfying way. The objects are not selectable but then you can still enter edit mode of the object which i would consider to be a bug as it defeats the purpose of having the object/collection non selectable. I will open a bug report with blender to see what they have to say about this. 
I can make it that the button will not be disabled with such objects but the clipping will not work on them as they are not valid targets for the distance calculation.

**Comment by Intuos5** [comment]
That's strange indeed, but I suspect that as with most quirks in Blender, it's by design. Even though there's no apparent benefit to it, usually the devs say it's part of the design. I guess in this case that they want it so that objects can't be selected in the viewport and that it's not meant to actually lock objects.

E: Can the bounding boxes of unselectable objects still be used for distance calculation?

**Comment by kromar** [comment]
I changed the poll so the button is not freezing in this scenario but as mentioned before, with those selections the clipping calculation is not working. 
https://github.com/kromar/blender_clipping_assistant/releases/tag/V2_0_7

Yeah sometimes that is the case when reporting issues like this but there is always the chance of them not being aware of it and might change it.

I opened a report here in case you are curious to see what happens with it: https://projects.blender.org/blender/blender/issues/107198

`E: Can the bounding boxes of unselectable objects still be used for distance calculation?`
That is a good question, i will try to see if i can access something usable.

**Comment by kromar** [comment]
Good news, i found a way to get the outliner object and have a prototype working, i will need to spend some time to clean this up but it should eventually work!

**Comment by kromar** [comment]
this should provide a fix, one limitation is that only the last selected "non - selectable" object in the outliner is considered for the distance calculation but as long as the objects are not far apart it should not be a issue
https://github.com/kromar/blender_clipping_assistant/releases/tag/V2_0_8

**Comment by Intuos5** [comment]
Sounds good to me, thank you very much!

**Comment by Intuos5** [comment]
One thing I do notice is that because you change the addon name (in addition to the name of the zipped folder), the settings for the addon get reverted (Blender sees it as a new addon altogether this way). Not a big deal, but I do want to mention it. Apart from that it works pretty well! Thanks again!
